#!/usr/bin/env php
<?php
require_once __DIR__.'/../vendor/autoload.php';

if(file_exists(__DIR__.'../bootstrap/config.php'))
	include_once '../bootstrap/config.php';

if (!class_exists("Frameworkless\Console\Application")) {
    echo "Please run composer install" . PHP_EOL;
    die(1);
}

use Symfony\Component\Console\Application;
use Frameworkless\Console\Commands;

$command = new Commands\InfoCommand();
$application = new Application();
$application->add($command);
$application->setDefaultCommand($command->getName());

$application->add(new Commands\InstallPackagesCommand);
$application->add(new Commands\SeedCommand);
$application->add(new Commands\InstallCommand);

$application->add(new \Propel\Generator\Command\ConfigConvertCommand());
$application->add(new \Propel\Generator\Command\MigrationMigrateCommand());

$application->run();
